# Generated by Django 4.2.1 on 2023-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grades',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='composite_pk'),
        ),
    ]
