# Generated by Django 4.2 on 2023-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('Ain Shams University', 'Ain Shams University'), ('Cairo University', 'Cairo University'), ('Helwan University', 'Helwan University'), ('The American University in Cairo', 'The American University in Cairo'), ('German University in Cairo', 'German University in Cairo')], default='Cairo University', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
