# Generated by Django 4.2.1 on 2023-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_alter_student_options_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='grade',
            new_name='course_grade',
        ),
        migrations.AddField(
            model_name='registration',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
