# Generated by Django 4.2.1 on 2023-05-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_grades_composite_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='course_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='final_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
