# Generated by Django 4.2.1 on 2023-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_rename_grade_registration_course_grade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Grades',
        ),
    ]
