# Generated by Django 4.2.1 on 2023-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_rename_registration_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='course_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='final_grade',
            field=models.IntegerField(null=True),
        ),
    ]
